# OAuth Configuration
hwi_oauth:
    firewall_name: main
    resource_owners:
        vkontakte:
            type:             vkontakte
            client_id:        "4602253"
            client_secret:    "68ZtvU4VMVohGyGk1tjN"
            scope:            "email"

        github:
            type:             github
            client_id:        "4586d58a3dbf045e178e"
            client_secret:    "99225fedb2d3ce7044a61ee29e7e7cb8600f1bc0"
            scope:            "user:email"

        facebook:
            type:             facebook
            client_id:        "278935655649323"
            client_secret:    "9005fb2aee66302e460da34160624002"
            scope:            "email"
