vkontakte_login:
    pattern: /authorization/check-vkontakte

vkontakte_connect:
    pattern: /connect/check-vkontakte

github_login:
    pattern: /authorization/check-github

github_connect:
    pattern: /connect/check-github

facebook_login:
    pattern: /authorization/check-facebook

facebook_connect:
    pattern: /connect/check-facebook
