security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory: ~

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:      fos_userbundle
                login_path:    fos_user_security_login
                check_path:    fos_user_security_check
                default_target_path: fos_user_profile_show
                csrf_provider: form.csrf_provider
#                remember_me:   true
#            remember_me:
#                key:      %secret%
            logout:
                path:     fos_user_security_logout
                target:   fos_user_security_login
            anonymous:    true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/admin/, role: ROLE_ADMIN }
