services:
    sonata.admin.user:
        class: Network\StoreBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: user }
        arguments:
            - ~
            - Network\StoreBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
    sonata.admin.group:
        class: Network\StoreBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: group }
        arguments:
            - ~
            - Network\StoreBundle\Entity\Group
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
    sonata.admin.contact:
        class: Network\StoreBundle\Admin\ContactAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: ContactsInfo, show_in_dashboard: false  }
        arguments:
            - ~
            - Network\StoreBundle\Entity\ContactInfo
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
    sonata.admin.address:
        class: Network\StoreBundle\Admin\ContactAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: address }
        arguments:
            - ~
            - Network\StoreBundle\Entity\Address
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
    sonata.admin.phone:
        class: Network\StoreBundle\Admin\ContactAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: phonenumber, enabled: false, show_in_dashboard: false  }
        arguments:
            - ~
            - Network\StoreBundle\Entity\Phonenumber
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]

    sonata.admin.country:
        class: Network\StoreBundle\Admin\SchoolAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: country }
        arguments:
            - ~
            - Network\StoreBundle\Entity\Country
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
            - [ setTemplate, [edit, NetworkStoreBundle:School:edit.html.twig]]
    sonata.admin.city:
        class: Network\StoreBundle\Admin\SchoolAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: city }
        arguments:
            - ~
            - Network\StoreBundle\Entity\City
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
            - [ setTemplate, [edit, NetworkStoreBundle:School:edit.html.twig]]
    sonata.admin.university:
        class: Network\StoreBundle\Admin\SchoolAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: university }
        arguments:
            - ~
            - Network\StoreBundle\Entity\University
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
            - [ setTemplate, [edit, NetworkStoreBundle:School:edit.html.twig]]
    sonata.admin.faculty:
        class: Network\StoreBundle\Admin\SchoolAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: faculty }
        arguments:
            - ~
            - Network\StoreBundle\Entity\Faculty
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
            - [ setTemplate, [edit, NetworkStoreBundle:School:edit.html.twig]]
    sonata.admin.chair:
        class: Network\StoreBundle\Admin\SchoolAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: chair }
        arguments:
            - ~
            - Network\StoreBundle\Entity\Chair
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
            - [ setTemplate, [edit, NetworkStoreBundle:School:edit.html.twig]]
    sonata.admin.school:
        class: Network\StoreBundle\Admin\SchoolAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: school }
        arguments:
            - ~
            - Network\StoreBundle\Entity\School
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
            - [ setTemplate, [edit, NetworkStoreBundle:School:edit.html.twig]]


sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
