services:
    sonata.admin.user:
        class: Network\StoreBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: user }
        arguments:
            - ~
            - Network\StoreBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
    sonata.admin.group:
        class: Network\StoreBundle\Admin\GroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: group }
        arguments:
            - ~
            - Network\StoreBundle\Entity\Group
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
    sonata.admin.contact:
        class: Network\StoreBundle\Admin\ContactAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: ContactsInfo, show_in_dashboard: false  }
        arguments:
            - ~
            - Network\StoreBundle\Entity\ContactInfo
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
    sonata.admin.address:
        class: Network\StoreBundle\Admin\ContactAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: address }
        arguments:
            - ~
            - Network\StoreBundle\Entity\Address
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]
    sonata.admin.phone:
        class: Network\StoreBundle\Admin\ContactAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: phonenumber, enabled: false, show_in_dashboard: false  }
        arguments:
            - ~
            - Network\StoreBundle\Entity\Phonenumber
            - ~
        calls:
            - [ setTranslationDomain, [NetworkStoreBundle]]

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
