mainpage:
    path:     /
    defaults: { _controller: NetworkWebBundle:Default:index }

user_jobs_profile:
  path: /profile/jobs
  defaults: { _controller: NetworkWebBundle:User:jobs }

kladr_test_page:
    path:     /test/kladr
    defaults: { _controller: NetworkWebBundle:Kladr:test }
