mainpage:
    path:     /
    defaults: { _controller: NetworkWebBundle:Default:index }

user_profile_editing:
    path: /user/{id}/profile/
    defaults: { _controller: NetworkWebBundle:User:profile }
    requirements:
       id: \d+

kladr_test_page:
    path:     /test/kladr
    defaults: { _controller: NetworkWebBundle:Kladr:test }
