network_web_homepage:
    path:     /hello/{name}
    defaults: { _controller: NetworkWebBundle:Default:index }

# smth_login:
#     path:     /login
#     defaults: { _controller: NetworkWebBundle:Auth:login }
