parameters:
#    network_web.example.class: Network\WebBundle\Example

services:
#    network_web.example:
#        class: %network_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
